version: '3.1'

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'flaskDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted

    volumes:
      - vol1:/var/lib/mysql


  #Frontend Service
  client:
    container_name: flaskapp
    build: .
    ports:
      - 5000:5000
    environment:
       MYSQL_DB: flaskDB
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_HOST: mysqldb
       MYSQL_PORT: 3306
    depends_on:
      - mysqldb

volumes:
  vol1:
